version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - 9000:80
    networks:
        network: 
          ipv4_address: 172.10.0.2
    volumes:
      - ./loadbalance/:/etc/nginx/conf.d/
  
  front1:
    image: node:16.17.0
    working_dir: /home/node/app
    ports:
      - 9001:80
    networks:
        network: 
          ipv4_address: 172.10.0.3
    volumes:
      - .:/home/node/app/:ro
    command: "npm start"

  front2:
    image: node:16.17.0
    working_dir: /home/node/app
    ports:
      - 9002:80
    networks:
        network: 
          ipv4_address: 172.10.0.4
    volumes:
      - .:/home/node/app/:ro
    command: "npm start"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1